[package]
name = "embedded-sdk-board-xiao-esp32c6"
description = "Board support metadata for Seeed Studio XIAO ESP32C6"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.embedded-sdk.board]
id = "xiao-esp32c6"
target = "riscv32imac-unknown-none-elf"
runner = ["espflash", "flash", "--monitor"]

[dependencies]
embedded-sdk-bluetooth.workspace = true
embedded-sdk-core.workspace = true
embedded-sdk-platform-esp32c6.workspace = true

[lints]
workspace = true
