[package]
name = "xtask"
description = "Repository automation for embedded-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
embedded-sdk-provisioning.workspace = true
serialport.workspace = true
xiao-esp32c6-config.workspace = true
zeroize.workspace = true

[lints]
workspace = true
